#  A schemas.py file is where you define your Pydantic data models — 
# it is the file that defines the shape and rules of the data flowing in and out of your API
# Just like APIRouter helped you organize your routes into separate files,
#  schemas.py keeps all your data models in one place — separate from your routes and business logic

# Enum is a built in Python class that lets you define a fixed set of
# named constants. It prevents invalid values from being used by restricting
# choices to only what you define
# BaseModel is the base class from Pydantic that all our data models inherit from
# Field is a Pydantic tool that lets you add extra validation rules to a field
# beyond just the type hint, like min/max length
# Optional is from Python's typing module — it means a field can either be
# its defined type OR None
from enum import Enum
from pydantic import BaseModel, Field
from typing import Optional

'''
IMPORTANT NOTE: 

When a client sends a JSON request to your FastAPI application, 
Uvicorn receives it and passes it to FastAPI via the ASGI interface.
 astAPI then automatically converts the raw JSON into the Pydantic model you defined,
validating it against your schema at the same time — rejecting it with a 422 error if it does not match. 
Your business logic then runs entirely in Python, working with clean, validated Python objects.
When you return a response, FastAPI automatically converts your Python object back to JSON
and passes it back through Uvicorn to the client — meaning you never have to manually handle JSON conversion at any point,
it all happens automatically at the boundaries of your application.
'''


# IssueStatus is an Enum that defines the only valid statuses an issue can have
# By inheriting from both str and Enum:
# - str means the values are strings, so they serialize to JSON cleanly
# - Enum means only these three values are ever allowed
# If anyone tries to pass "deleted" or "pending" as a status, Pydantic will reject it
class IssueStatus(str, Enum):
  open = "open"
  in_progress = "in_progress"
  closed = "closed"


# Same concept as IssueStatus but for priority levels
# An issue can only ever be low, medium, or high priority
# Any other value will be rejected by Pydantic automatically
class IssuePriority(str, Enum):
  low = "low"
  medium = "medium"
  high = "high"


# IssueCreate defines the shape of data the CLIENT must send
# when creating a new issue
# It inherits from BaseModel which gives it all Pydantic validation powers
class IssueCreate(BaseModel):

  # title must be a string with at least 3 characters and at most 100 characters
  # Field() lets us add these extra validation rules beyond just the str type hint
  # If the client sends a title that is too short or too long, Pydantic returns a 422 error
  title: str = Field(min_length=3, max_length=100)

  # description must be a string with at least 5 and at most 1000 characters
  description: str = Field(min_length=5, max_length=1000)

  # priority must be one of the values defined in IssuePriority enum
  # IssuePriority.medium is the DEFAULT value — if the client does not send
  # a priority, it automatically defaults to "medium"
  priority: IssuePriority = IssuePriority.medium


# IssueUpdate defines the shape of data the CLIENT sends
# when UPDATING an existing issue
# Notice every field is Optional — this is intentional because when updating,
# the client should only need to send the fields they want to change
# not the entire issue all over again
class IssueUpdate(BaseModel):

  # Optional[str] means title can either be a string OR None
  # default=None means if the client does not send a title, it defaults to None
  # meaning "do not update this field"
  # max_length=100 still enforces the length rule if a value IS provided
  title: Optional[str] = Field(default=None, max_length=100)

  # Same as title — optional, defaults to None, max 1000 characters if provided
  description: Optional[str] = Field(default=None, max_length=1000)

  # Optional priority — if not provided, defaults to None meaning "do not update"
  priority: Optional[IssuePriority] = None

  # Optional status — allows updating the status of an issue
  # e.g. moving it from "open" to "in_progress" or "closed"
  status: Optional[IssueStatus] = None


# IssueOut defines the shape of data the SERVER sends BACK to the client
# in responses — notice it has ALL fields including id and status
# which the client never sends when creating an issue
# id is generated by the server, status defaults to "open" on creation
class IssueOut(BaseModel):
  # id is a string — this suggests UUIDs are being used as identifiers
  # rather than simple incrementing integers like 1, 2, 3
  id: str
  title: str
  description: str
  priority: IssuePriority
  # status is always present in responses so the client knows
  # the current state of the issue
  status: IssueStatus